spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${LB_AUTH_ISSUER_URI}
      client:
        registration:
          msvc-users-client:
            provider: spring
            client-id: users-client
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: ${LB_USERS_URI}/authorized
            scope: read
            client-name: msvc-users-client
        provider:
          spring:
            issuer-uri: ${LB_AUTH_ISSUER_URI}