apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-users
data:
  port: "8001"
  db_host: mysql8
  db_port: "3306"
  db_database: msvc_users
  db_username: root
  db_password: sa123123
  courses_url: "msvc-courses:8002"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-courses
data:
  port: "8002"
  db_host: postgres15
  db_port: "5432"
  db_database: msvc_courses
  db_username: postgres
  db_password: sa123123
  users_url: "msvc-users:8001"
