apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: msvc-users
  name: msvc-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-users
  template:
    metadata:
      labels:
        app: msvc-users
    spec:
      containers:
      - image: djblancoh/users:latest
        name: users
        ports:
        - containerPort: 8001
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: msvc-users
                key: port
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: msvc-users
                key: db_host
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: msvc-users
                key: db_port
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: msvc-users
                key: db_database
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: msvc-users
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: msvc-users
                key: password
          - name: COURSES_URL
            valueFrom:
              configMapKeyRef:
                name: msvc-users
                key: courses_url
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8001
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 20
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8001
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 20
        resources:
          requests:
            memory: "512Mi"
            cpu: "400m"
          limits:
            memory: "800Mi"
            cpu: "500m"

