apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres15
spec:
  replicas: 1
  selector:
    matchLabels:
      role: postgres
  template:
    metadata:
      labels:
        role: postgres
    spec:
      containers:
        - image: postgres:15-alpine
          name: postgres15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: sa123123
            - name: POSTGRES_DB
              value: msvc_courses
          volumeMounts:
            - name: data-postgres
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data-postgres
          hostPath:
            path: /var/lib/postgresql/data
            type: DirectoryOrCreate