version: "3.9"

services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sa123123
      MYSQL_DATABASE: msvc_users
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always

    networks:
      - spring

  postgres15:
    container_name: postgres15
    image: postgres:15-alpine
    ports:
      -  "5532:5432"
    environment:
      POSTGRES_PASSWORD: sa123123
      POSTGRES_DB: msvc_courses
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  msvc-users:
    container_name: msvc-users
    image: djblancoh/users
#    build:
#      context: ./
#      dockerfile: ./msvc-users/Dockerfile

    ports:
      - "8001:8001"
#    env_file: ./msvc-users/.env
    environment:
      PORT: 8001
      DB_HOST: mysql8
      DB_PORT: 3306
      DB_DATABASE: msvc_users
      DB_USERNAME: root
      DB_PASSWORD: sa123123
      COURSES_URL: msvc-courses:8002
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always

  msvc-courses:
    container_name: msvc-courses
    image: djblancoh/courses
#    build:
#      context: ./
#      dockerfile: ./msvc-courses/Dockerfile
    ports:
      - "8002:8002"
#    env_file:
#      - ./msvc-courses/.env
    environment:
      PORT: 8002
      DB_HOST: postgres15
      DB_PORT: 5432
      DB_DATABASE: msvc_courses
      DB_USERNAME: postgres
      DB_PASSWORD: sa123123
      USERS_URL: msvc-users:8001

    networks:
      - spring
    depends_on:
      - postgres15
      - msvc-users
    restart: always


volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres

networks:
  spring:
